swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api
# In order to see the swagger ui, make sure you have done.
# sudo pip install swagger-ui-bundle
# Then open http://localhost:5000/api/ui/#!/


# Paths supported by the server application
paths:
  /led:
    get:
      operationId: led.aus
      tags:
        - led
      summary: Read the entire list of led
      description: Read the list of led
      responses:
        200:
          description: Successfully read led list operation
          schema:
            type: array
            items:
              properties:
                minutes:
                  type: string
                passw:
                  type: string

    post:
      operationId: led.ein
      tags:
        - led
      summary: Send a message to turn on the LED
      description: Send a message to turn on the LED
      parameters:
        - name: params
          in: body
          description: Send a message to turn on the LED
          required: True
          schema:
            type: object
            properties:
              minutes:
                type: string
                description: How long to turn on the LED
              passw:
                type: string
                description: Secret to use the API
      responses:
        201:
          description: Successfully called the API

  /led2:
    get:
      operationId: led.aus2
      tags:
        - led
      summary: Turn LED 2 off
      description: Turn LED 2 off
      responses:
        200:
          description: Successfully turned LED 2 off
          schema:
            type: array
            items:
              properties:
                minutes:
                  type: string
                passw:
                  type: string

    post:
      operationId: led.ein2
      tags:
        - led
      summary: Send a message to turn on the LED
      description: Send a message to turn on the LED
      parameters:
        - name: params
          in: body
          description: Send a message to turn on the LED
          required: True
          schema:
            type: object
            properties:
              minutes:
                type: string
                description: How long to turn on the LED
              passw:
                type: string
                description: Secret to use the API
      responses:
        201:
          description: Successfully called the API

  /stats:
    get:
      operationId: stats.howlong
      tags:
        - stats
      summary: Check how long the LED has been on
      description: Check how long the LED has been on
      responses:
        200:
          description: Successfully read how long
          schema:
            type: array
            items:
              properties:
                uptime:
                  type: string